/**:
  ros__parameters:
    cloud_ip: "127.0.0.1"
    manage_port: 26565
    sub_clock: true
    sub_list:
    - scan
    - tf_static
    - odom
    - imu
    - initialpose
    - move_simple
    - clock
    - bt_elev
    - bt_elev_cancel
    - front_color_compressed
    - goal_pose
    - demo_node_talker
    tf_list:
    - odom_basefootprint
    srv_server_list:
    - load_map
    - core_GetDeviceId
    srv_client_list:
    - add_two_ints
