/**:
  ros__parameters:
    use_sim_time: True
    
    scan:
      topic: "scan"
      msg: "sensor_msgs/msg/LaserScan"
      qos: "sensor_data"

    tf:
      topic: "tf"
      msg: "tf2_msgs/msg/TFMessage"

    tf_static:
      topic: "tf_static"
      msg: "tf2_msgs/msg/TFMessage"

    odom:
      topic: "odom"
      msg: "nav_msgs/msg/Odometry"

    cmd_vel:
      topic: "cmd_vel"
      msg: "geometry_msgs/msg/Twist"
      qos: "sensor_data"

    imu:
      topic: "imu"
      msg: "sensor_msgs/msg/Imu"
      qos: "sensor_data"

    clock:
      topic: "/clock"
      msg: "rosgraph_msgs/msg/Clock"

    plan:
      topic: "plan"
      msg: "nav_msgs/msg/Path"
      qos: "sensor_data"

    map:
      topic: "map"
      msg: "nav_msgs/msg/OccupancyGrid"

    initialpose:
      topic: "initialpose"
      msg: "geometry_msgs/msg/PoseWithCovarianceStamped"
      qos: "sensor_data"

    move_simple:
      topic: "move_base_simple/goal"
      msg: "geometry_msgs/msg/PoseStamped"
      qos: "sensor_data"

    goal_pose:
      topic: "goal_pose"
      msg: "geometry_msgs/msg/PoseStamped"
      qos: "sensor_data"

    footprint:
      topic: "global_costmap/published_footprint"
      msg: "geometry_msgs/msg/PolygonStamped"

    load_map:
      service: "load_map"
      srv: "nav2_msgs/srv/LoadMap"
    
    map_odom:
      base_frame: "map"
      child_frame: "odom"

    odom_basefootprint:
      base_frame: "odom"
      child_frame: "base_footprint"

    odom_right_wheel:
      base_frame: "base_link"
      child_frame: "RightWheel_link"      

    call_elevator:
      service: "/elevator_system/call_elevator"
      srv: "elevator_system_msgs/srv/CallElevator"

    get_called_elevator:
      service: "/elevator_system/get_called_elevator"
      srv: "elevator_system_msgs/srv/CallElevator"

    get_elevator_information:
      service: "/elevator_system/get_elevator_information"
      srv: "elevator_system_msgs/srv/GetElevatorInformation"

    is_door_opened:
      service: "/elevator_system/is_door_opened"
      srv: "elevator_system_msgs/srv/RequestDoor"

    request_door_open:
      service: "/elevator_system/request_door_open"
      srv: "elevator_system_msgs/srv/RequestDoor"

    select_elevator_floor:
      service: "/elevator_system/select_elevator_floor"
      srv: "elevator_system_msgs/srv/SelectElevatorFloor"

    bt_elev:
      topic: "navigate_with_elevator"
      msg: "std_msgs/msg/String"

    bt_elev_feedback:
      topic: "navigate_with_elevator/feedback"
      msg: "std_msgs/msg/String"
    
    bt_elev_result:
      topic: "navigate_with_elevator/result"
      msg: "std_msgs/msg/String"

    bt_elev_cancel:
      topic: "navigate_with_elevator/cancel"
      msg: "std_msgs/msg/Empty"
    
    nav2_status:
      topic: "NavigateToPose/_action/status"
      msg: "action_msgs/msg/GoalStatusArray"

    color_compressed:
      topic: "front/color/image_raw/compressed"
      msg: "sensor_msgs/msg/CompressedImage"
    
    add_two_ints:
      service: "/add_two_ints"
      srv: "example_interfaces/srv/AddTwoInts"

    demo_node_talker:
      topic: "/chatter"
      msg: "std_msgs/msg/String"
      qos: "system_default"

    core_registerRobot:
      service: "/core_registerRobot"
      srv: "ebme_interfaces/srv/RegisterInfo"

    core_sendActionInfo:
      service: "/core_sendActionInfo"
      srv: "ebme_interfaces/srv/ActionInfo"

    core_sendBatteryInfo:
      service: "/core_sendBatteryInfo"
      srv: "ebme_interfaces/srv/BatteryInfo"

    core_sendDeviceState:
      service: "/core_sendDeviceState"
      srv: "ebme_interfaces/srv/Device"

    core_sendErrorInfo:
      service: "/core_sendErrorInfo" 
      srv: "ebme_interfaces/srv/ErrorInfo"

    core_sendExpendableInfo:
      service: "/core_sendExpendableInfo"
      srv: "ebme_interfaces/srv/ExpendableInfo"

    core_sendLocationInfo:
      service: "/core_sendLocationInfo"
      srv: "ebme_interfaces/srv/LocationInfo"

    core_sendMessage:
      service: "/core_sendMessage"
      srv: "ebme_interfaces/srv/Message"

    core_sendModeInfo:
      service: "/core_sendModeInfo"
      srv: "ebme_interfaces/srv/ModeInfo"

    core_sendPushMessage:
      service: "/core_sendPushMessage"
      srv: "ebme_interfaces/srv/PushMessage"

    core_sendRobotExpendableListInfo:
      service: "/core_sendRobotExpendableListInfo"
      srv: "ebme_interfaces/srv/ExpendableInfo"

    core_sendRobotMapListInfo:
      service: "/core_sendRobotMapListInfo"
      srv: "ebme_interfaces/srv/MapInfo"

    core_sendRobotMovePathListInfo:
      service: "/core_sendRobotMovePathListInfo"
      srv: "ebme_interfaces/srv/MovePathInfo"

    core_sendRobotPoiListInfo:
      service: "/core_sendRobotPoiListInfo"
      srv: "ebme_interfaces/srv/PoiInfo"

    core_sendRobotResourceListInfo:
      service: "/core_sendRobotResourceListInfo"
      srv: "ebme_interfaces/srv/ResourceInfo"

    core_sendRobotSensorListInfo:
      service: "/core_sendRobotSensorListInfo"
      srv: "ebme_interfaces/srv/SensorInfo"

    core_sendSensorInfo:
      service: "/core_sendSensorInfo"
      srv: "ebme_interfaces/srv/SensorInfo"

    core_unregisterRobot:
      service: "/core_unregisterRobot"
      srv: "ebme_interfaces/srv/RegisterInfo"
