/**:
  ros__parameters:
    manage_port: 26565
    sub_port: 26566
    pub_port: 26567
    req_port: 26568
    rep_port: 26569
    host_sub_port: 26566
    host_pub_port: 26567
    host_req_port: 26568
    host_rep_port: 26569  
    sub_list:
    - cmd_vel
    - plan
    - footprint
    - map
    - bt_elev_feedback
    - bt_elev_result
    - nav2_status
    tf_list:
    - map_odom
    srv_server_list:
    - call_elevator
    - get_called_elevator
    - get_elevator_information
    - is_door_opened
    - request_door_open
    - select_elevator_floor
    - add_two_ints
    srv_client_list:
    - load_map
